[package]
name = "binius-mayo"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
binius-core       = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-frontend   = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-circuits   = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-transcript = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-prover     = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-verifier   = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
binius-hash       = { git = "https://github.com/binius-zk/binius64", rev = "3bc7451dc3c52af6383fcd99892c6892f57e89b0" }
sha3              = "=0.10.9"
aes               = "=0.8.4"
rand              = "0.10"

[dev-dependencies]
hex               = "0.4"
rand              = "0.10"
criterion         = "0.5"

[[bench]]
name    = "prove_verify"
harness = false

[profile.release]
lto = "thin"
